spring:
  application:
    name: "metadium-did-resolver"
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 3030
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

# Logging config
logging:
#  file:
#    path: "./log"
#    max-size: 10MB
#    max-history: 30
  level:
    # Change below to change application logging level
    io.omnipede.metadium.did.resolver: INFO

resolver:
  driverId: "did-meta"

# IdentityHub configuration
identityHub:
  id: "did:meta:0000000000000000000000000000000000000000000000000000000000000527"
  url: "https://datahub.metadium.com"

# Metadium blockchain configuration
metadium:
  network: 'mainnet'
  http-provider: 'https://api.metadium.com/prod'
  identityRegistry-address: "0x42bbff659772231bb63c7c175a1021e080a4cf9d"
  publicKeyResolver-address-list:
    - "0xd9f39ab902f835400cfb424529bb0423d7342331"
  serviceKeyResolver-address-list:
    - "0x5d4b8c6c6abecf9b5277747fa15980b964c40ce3"
